/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Entidad.HistoricoDatos;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class PanelTablaDatos extends javax.swing.JPanel {
    
    private EntityManagerFactory 
            emf = Persistence.createEntityManagerFactory("Parcial2PU");
    /**
     * Creates new form PanelTablaDatos
     */
    public PanelTablaDatos() {
        initComponents();
    }
    
    public void llenarTabla() {
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("SELECT h FROM HistoricoDatos h ORDER BY h.id DESC");
        List<HistoricoDatos> listaDatos = q.getResultList();
        
        DefaultTableModel model = (DefaultTableModel) jtableDatos.getModel();
        
        int numDatos = model.getRowCount();
        for (int i = 0; i < numDatos; i++) {
            model.removeRow(0);
        }
        
        int i = 0;
        for (HistoricoDatos h : listaDatos) {
            int idSensor = h.getSensor().getId();
            double valorTomado = h.getValorTomado();
            String fecha = h.getFecha();
            String hora = h.getHora();
            String procesamiento = h.getProcesamiento();

            model.addRow(new Object[]{idSensor,
                valorTomado,
                fecha,
                hora,
                procesamiento});
            i++;
            if (i == 5) {
                break;
            }
        }

    }

    public JLabel getJlFecha() {
        return jlFecha;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtableDatos = new javax.swing.JTable();
        jlTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlFecha = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jtableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Sensor", "Valor Tomado", "Fecha", "Hora", "Procesamiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtableDatos);
        if (jtableDatos.getColumnModel().getColumnCount() > 0) {
            jtableDatos.getColumnModel().getColumn(0).setResizable(false);
            jtableDatos.getColumnModel().getColumn(1).setResizable(false);
            jtableDatos.getColumnModel().getColumn(2).setResizable(false);
            jtableDatos.getColumnModel().getColumn(3).setResizable(false);
            jtableDatos.getColumnModel().getColumn(4).setResizable(false);
        }

        jlTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlTitulo.setText("Últimos 5 datos tomados");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Fecha: ");

        jlFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlTitulo))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jlFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTable jtableDatos;
    // End of variables declaration//GEN-END:variables
}
